server:
  port: 8088
  servlet:
    context-path: /api/gilded-rose

spring:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./h2-db/gildedrose;AUTO_SERVER=TRUE
    username: gildedrose
    password: gildedrose
    driverClassName: org.h2.Driver

surgePricing:
  durationInMinutes: 60
  viewCountsTriggerPriceIncrease: 11
  percentageIncrease: 10

findAllItems:
  pageSize: 100

ordering:
  user: foo
  password: bar
